"""Soul Cradle — shared DNA/constitution for the Mythara organism.

The membrane every cell's signals pass through. Start with
soul_cradle.authorization: signed action envelopes that Aries verifies
before executing anything.
"""

from .authorization import (
    ActionEnvelope,
    AuthorizationError,
    SoulCradleAuthority,
    action_types,
    register_handler,
)
from .standing import (
    DECLARE_FORGIVENESS,
    DECLARE_REPENTANCE,
    DECLARE_TRESPASS,
    WITNESS_STATEMENT,
    STRANGER,
    TRESPASSER,
    WITNESS,
    WRONGED,
    Declaration,
    StandingAuthority,
    StandingError,
    evaluate_standing,
)
from .forge import Bond, Compound, Forge, ForgeError
from .identity import (
    GENDER,
    NAME,
    PRONOUNS,
    VOICE_CHARACTER,
    VOICE_DESCRIPTION,
    VOICE_GENDER,
    get_identity,
)
from .will import ALLOW, ESCALATE, Will, WillError, check as will_check, scan_text
from .assessors import (
    ABSTAIN,
    CLEAR as ASSESSOR_CLEAR,
    FLAGGED as ASSESSOR_FLAGGED,
    PANEL_BLOCKED,
    PANEL_CLEAR,
    PANEL_CONTESTED,
    PANEL_FLAGGED,
    ASSESSORS,
    AssessorJudgment,
    AssessorSpec,
    PanelResult,
    RubricCheck,
    assessor_bounds_check,
    assessor_witness_declaration,
    consult as consult_assessor,
    panel as assessor_panel,
    rubric_inventory as assessor_rubric_inventory,
    verify_judgment as verify_assessor_judgment,
)

__all__ = [
    "ActionEnvelope",
    "AuthorizationError",
    "SoulCradleAuthority",
    "action_types",
    "register_handler",
    "DECLARE_FORGIVENESS",
    "DECLARE_REPENTANCE",
    "DECLARE_TRESPASS",
    "WITNESS_STATEMENT",
    "STRANGER",
    "TRESPASSER",
    "WITNESS",
    "WRONGED",
    "Declaration",
    "StandingAuthority",
    "StandingError",
    "evaluate_standing",
    "Bond",
    "Compound",
    "Forge",
    "ForgeError",
    "GENDER",
    "NAME",
    "PRONOUNS",
    "VOICE_CHARACTER",
    "VOICE_DESCRIPTION",
    "VOICE_GENDER",
    "get_identity",
    "ALLOW",
    "ESCALATE",
    "Will",
    "WillError",
    "will_check",
    "scan_text",
    "ABSTAIN",
    "ASSESSOR_CLEAR",
    "ASSESSOR_FLAGGED",
    "PANEL_BLOCKED",
    "PANEL_CLEAR",
    "PANEL_CONTESTED",
    "PANEL_FLAGGED",
    "ASSESSORS",
    "AssessorJudgment",
    "AssessorSpec",
    "PanelResult",
    "RubricCheck",
    "assessor_bounds_check",
    "assessor_witness_declaration",
    "consult_assessor",
    "assessor_panel",
    "assessor_rubric_inventory",
    "verify_assessor_judgment",
]
